name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Initialize build number
      run: |
        if [ ! -f "build_number.txt" ]; then
          echo "0" > build_number.txt
        fi
      if: matrix.os == 'ubuntu-latest'

    - name: Initialize build number (Windows)
      run: |
        if (-not (Test-Path "build_number.txt")) {
          "0" | Out-File -FilePath "build_number.txt" -Encoding utf8
        }
      if: matrix.os == 'windows-latest'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    
    - name: Run executable
      run: ${{ matrix.os == 'windows-latest' && '.\build\Release\hello_world.exe' || './build/hello_world' }}
